version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/foodmarketdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d/

volumes:
  mongo-data:
