db = db.getSiblingDB("foodmarketdb"); // Назва бази даних

const products =   [
  {
    "name": "Fresh Atlantic Salmon",
    "image": [
      "https://allfreshseafood.com/cdn/shop/files/2salmonfilletscanadian_1.jpg?v=1698852411",
      "https://www.samuelsseafood.com/wp-content/uploads/2016/11/Wild-Isle-whole-and-side-fillet-1.jpg",
      "https://m.media-amazon.com/images/I/817y+lN3ohL.jpg"
    ],
    "price": 15.99,
    "SKU": 10067890,
    "category": "MEATANDFISH",
    "subcategory": "FISH",
    "farm": "Northern Waters Fisheries",
    "stoke": "INSTOCK",
    "freshness": 5,
    "buyBy": ["Weight", "Piece"],
    "deliveryDays": 3,
    "deliveryCoast": 0,
    "deliveryAria": "USA",
    "maxKgs": 30,
    "description": "Fresh Atlantic salmon fillets, perfect for grilling or baking.",
    "detailDescription": "Our Atlantic salmon is sustainably sourced and rich in Omega-3 fatty acids. Ideal for a healthy diet.",
    "rate": 4.9,
    "tax": 8,
    "createdAt": "2025-01-04T14:00:00.000Z",
    "createdBy": "Admin 2",
    "updatedAt": "2025-01-04T14:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Organic Bananas",
    "image": [
      "https://www.chiquita.com/wp-content/uploads/2020/01/Chiquita_Organicsbananas_US_Yellow.jpg",
      "https://www.melissas.com/cdn/shop/products/image-of-organic-bananas-organics-14763756421164_600x600.jpg?v=1616958064",
      "https://spud-res.cloudinary.com/w_600/f_auto,q_auto,c_fill,w_600,e_improve:30,e_sharpen:60/spudca/Products/Bananas_Overripe_Imperfect_SI556600.jpg"
    ],
    "price": 2.99,
    "SKU": 10012345,
    "category": "FRUITANDVEGETABLES",
    "subcategory": "FRUIT",
    "farm": "Green Valley Farm",
    "stoke": "INSTOCK",
    "freshness": 7,
    "buyBy": ["Weight", "Bunch"],
    "deliveryDays": 2,
    "deliveryCoast": 0.02,
    "deliveryAria": "USA and Canada",
    "maxKgs": 50,
    "description": "Fresh organic bananas perfect for smoothies and snacks.",
    "detailDescription": "These organic bananas are sourced from sustainable farms.",
    "rate": 4.8,
    "tax": 5,
    "createdAt": "2025-01-04T14:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-04T14:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Artisanal Whole Grain Bread",
    "image": [
      "https://ogden_images.s3.amazonaws.com/www.motherearthnews.com/images/2009/10/22112512/2009-12-dec-jan-artisan-bread-jpg.jpg",
      "https://bigoven-res.cloudinary.com/image/upload/f_auto,q_auto/t_recipe-1280/artisan-whole-grain-bread-reci-42b494.jpg",
      "https://joybileefarm.com/wp-content/uploads/2013/10/Multi-Grain-Artisan-Bread-in-5-Minutes-crop-feat-im.jpg"
    ],
    "price": 4.50,
    "SKU": 10054321,
    "category": "BAKERY",
    "subcategory": "BAKERY",
    "farm": "Golden Wheat Bakers",
    "stoke": "EXPECTEDSOON",
    "freshness": 3,
    "buyBy": ["Piece"],
    "deliveryDays": 1,
    "deliveryCoast": 0.5,
    "deliveryAria": "Worldwide",
    "maxKgs": 10,
    "description": "Nutritious and delicious artisanal whole grain bread.",
    "detailDescription": "This whole grain bread is baked fresh daily with the finest ingredients. High in fiber and perfect for a balanced diet.",
    "rate": 4.7,
    "tax": 2,
    "createdAt": "2025-01-01T08:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T10:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Organic Baby Spinach",
    "image": [
      "https://www.earthboundfarm.com/wp-content/uploads/2024/04/BabySpinach-Half-16oz-Mockup.jpg",
      "https://www.earthboundfarm.com/wp-content/uploads/2024/04/32601900205_newlook.jpg",
      "https://www.earthboundfarm.com/wp-content/uploads/2024/03/EBF-Baby-Spinach-5oz-Fiber-Less-Plastic-1.webp"
    ],
    "price": 3.99,
    "SKU": 10123456,
    "category": "FRUITANDVEGETABLES",
    "subcategory": "VEGETABLES",
    "farm": "Green Leaf Organics",
    "stoke": "INSTOCK",
    "freshness": 7,
    "buyBy": ["Bag", "Weight"],
    "deliveryDays": 2,
    "deliveryCoast": 0.01,
    "deliveryAria": "Local Only",
    "maxKgs": 20,
    "description": "Fresh organic baby spinach perfect for salads and smoothies.",
    "detailDescription": "This organic baby spinach is grown without pesticides and harvested at peak freshness. Packed with vitamins and minerals.",
    "rate": 4.8,
    "tax": 5,
    "createdAt": "2025-01-03T09:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-06T15:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Raw Honey",
    "image": [
      "https://beeconservation.org.uk/cdn/shop/products/Honey-in-jar-with-honey-dipper-honeycomb-and-lavender-flowers-on-the-side.jpg?v=1520255279",
      "https://terrapowders.com/cdn/shop/files/16ozFrontNatureNate_sHoneyCo100_PureAsNatureIntended_1445x.jpg?v=1682362056",
      "https://media.post.rvohealth.io/wp-content/uploads/sites/3/2024/09/raw-honey-732x549-thumbnail.jpg"
    ],
    "price": 12.99,
    "SKU": 10134567,
    "category": "SPECIALNUTRITION",
    "subcategory": "SPECIALNUTRITION",
    "farm": "Bee Bliss Farms",
    "stoke": "INSTOCK",
    "freshness": 365,
    "buyBy": ["Jar"],
    "deliveryDays": 5,
    "deliveryCoast": 0.05,
    "deliveryAria": "Worldwide",
    "maxKgs": 10,
    "description": "Pure raw organic honey harvested from sustainable hives.",
    "detailDescription": "Our honey is free from additives and processed using natural methods, ensuring premium quality and taste.",
    "rate": 4.9,
    "tax": 3,
    "createdAt": "2025-01-02T10:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T12:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Fresh Chicken Breast",
    "image": [
      "https://131263712.cdn6.editmysite.com/uploads/1/3/1/2/131263712/s972748746574077376_p71_i1_w2560.jpeg?width=2400&optimize=medium",
      "https://ldameatsltd.co.uk/wp-content/uploads/2023/07/Fresh-Chicken-Fillets.jpg",
      "https://wholesalemeatscoventry.co.uk/wp-content/uploads/2020/12/CMW-18.jpg"
    ],
    "price": 8.49,
    "SKU": 10145678,
    "category": "MEATANDFISH",
    "subcategory": "MEAT",
    "farm": "Sunny Farm Poultry",
    "stoke": "INSTOCK",
    "freshness": 5,
    "buyBy": ["Weight"],
    "deliveryDays": 2,
    "deliveryCoast": 0,
    "deliveryAria": "Nationwide",
    "maxKgs": 50,
    "description": "Premium quality fresh chicken breast with no added hormones.",
    "detailDescription": "Perfectly trimmed chicken breast, sourced from local farms. Ideal for healthy meals.",
    "rate": 4.6,
    "tax": 7,
    "createdAt": "2025-01-03T08:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-06T15:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Organic Almond Milk",
    "image": [
      "https://cdn.perishablenews.com/2023/01/a-dar4.jpg",
      "https://www.instacart.com/assets/domains/product-image/file/large_c7ccc745-8ede-48df-98b0-0e3aed467938.jpg",
      "https://www.califiafarms.com/static/7cf26892e29668a2c0247ee39af29dd8/d65af/Califia-Farms_Lindseyeats_White_Chili_Unsweetened_Almondmilk_Recipe-Shot_2023_1-4.jpg"
    ],
    "price": 4.99,
    "SKU": 10156789,
    "category": "DRINKS",
    "subcategory": "DRINKS",
    "farm": "Nutra Farms",
    "stoke": "INSTOCK",
    "freshness": 14,
    "buyBy": ["Bottle"],
    "deliveryDays": 3,
    "deliveryCoast": 0.03,
    "deliveryAria": "Local Only",
    "maxKgs": 15,
    "description": "Smooth and creamy almond milk made from organic almonds.",
    "detailDescription": "Unsweetened almond milk, dairy-free, and fortified with calcium and vitamin D.",
    "rate": 4.7,
    "tax": 5,
    "createdAt": "2025-01-02T09:30:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-05T14:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Farm Fresh Organic Eggs",
    "image": [
      "https://m.media-amazon.com/images/I/61F6Ks9j1KL._AC_UF894,1000_QL80_.jpg",
      "https://www.beverlybees.com/wp-content/uploads/2024/04/Screenshot_20240607_122500_Instagram.jpg",
      "https://playflightfarmbakery.com/cdn/shop/products/playflight_eggs_1200x1200.jpg?v=1652992343"
    ],
    "price": 6.50,
    "SKU": 10167890,
    "category": "KITCHEN",
    "subcategory": "KITCHEN",
    "farm": "Happy Hen Farms",
    "stoke": "EXPECTEDSOON",
    "freshness": 14,
    "buyBy": ["Carton"],
    "deliveryDays": 2,
    "deliveryCoast": 0.02,
    "deliveryAria": "Local Only",
    "maxKgs": 30,
    "description": "Freshly laid organic eggs from cage-free hens.",
    "detailDescription": "These eggs come from hens raised on organic feed, ensuring great taste and nutritional value.",
    "rate": 4.8,
    "tax": 2,
    "createdAt": "2025-01-01T11:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-06T16:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Herbal Tea",
    "image": [
      "https://m.media-amazon.com/images/I/61rtYVGbpDL._AC_UF894,1000_QL80_.jpg",
      "https://www.pravek.com/cdn/shop/articles/Herbal-Tea-benfits.jpg?v=1699680718",
      "https://www.goldentipstea.com/cdn/shop/articles/blog-GTHT_800x.png?v=1634820834"
    ],
    "price": 5.99,
    "SKU": 10189012,
    "category": "DRINKS",
    "subcategory": "DRINKS",
    "farm": "Nature's Cup",
    "stoke": "INSTOCK",
    "freshness": 180,
    "buyBy": ["Box"],
    "deliveryDays": 4,
    "deliveryCoast": 0.01,
    "deliveryAria": "Nationwide",
    "maxKgs": 20,
    "description": "Relaxing herbal tea made from organic ingredients.",
    "detailDescription": "Our herbal tea blend includes chamomile, peppermint, and lavender for a soothing experience.",
    "rate": 4.9,
    "tax": 5,
    "createdAt": "2025-01-03T11:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-06T17:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Premium Grass-Fed Beef Steak",
    "image": [
      "https://grassrunfarms.com/wp-content/uploads/2021/09/P_Prime-caseready_ribeye-steak.jpg",
      "https://perennialpasturesranch.com/cdn/shop/files/5_5598b23b-52b9-4340-b2b0-32987b839830.png?v=1710977878",
      "https://www.tastyfoodaffair.com/cdn/shop/files/young-prime-grass-fed-striploin-steak-246604_800x.jpg?v=1731055500"
    ],
    "price": 18.99,
    "SKU": 10200123,
    "category": "MEATANDFISH",
    "subcategory": "MEAT",
    "farm": "Grassland Farms",
    "stoke": "INSTOCK",
    "freshness": 4,
    "buyBy": ["Weight"],
    "deliveryDays": 1,
    "deliveryCoast": 1,
    "deliveryAria": "Nationwide",
    "maxKgs": 20,
    "description": "Juicy, tender grass-fed beef steaks for gourmet meals.",
    "detailDescription": "Our premium beef steaks are 100% grass-fed, offering exceptional flavor and quality.",
    "rate": 4.8,
    "tax": 6,
    "createdAt": "2025-01-05T09:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T10:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Organic Chicken Thighs",
    "image": [
      "https://i5.walmartimages.com/seo/Freshness-Guaranteed-Boneless-Skinless-Chicken-Thighs-2-75-4-0-lb-Tray_8d322aa9-8df3-4777-8ee4-7eab035867dc.8f0b38d12ee415368873227f44d30c6a.jpeg",
      "https://alinggemma.com/cdn/shop/products/ChickenThigh_800x800px.png?v=1637140842",
      "https://static01.nyt.com/images/2024/01/04/multimedia/LH-Baked-Chicken-Thighs-hzgq/LH-Baked-Chicken-Thighs-hzgq-mediumSquareAt3X.jpg"
    ],
    "price": 7.49,
    "SKU": 10200234,
    "category": "MEATANDFISH",
    "subcategory": "MEAT",
    "farm": "Healthy Choice Poultry",
    "stoke": "INSTOCK",
    "freshness": 6,
    "buyBy": ["Weight", "Piece"],
    "deliveryDays": 2,
    "deliveryCoast": 0.02,
    "deliveryAria": "Local Only",
    "maxKgs": 15,
    "description": "Tender organic chicken thighs with no added hormones.",
    "detailDescription": "Perfect for grilling, roasting, or stewing, our chicken thighs are free-range and organically raised.",
    "rate": 4.7,
    "tax": 5,
    "createdAt": "2025-01-04T11:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-07T13:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Wild-Caught Salmon Fillets",
    "image": [
      "https://images.albertsons-media.com/is/image/ABS/960122401?$ng-ecom-pdp-mobile$&defaultImage=Not_Available",
      "https://wildalaskasalmonandseafood.com/wp-content/uploads/2021/05/kingrawb17.jpg",
      "https://wildalaskasalmonandseafood.com/wp-content/uploads/2021/05/Sockeye-Samon-Fillet_1000x628.jpg"
    ],
    "price": 14.99,
    "SKU": 10200345,
    "category": "MEATANDFISH",
    "subcategory": "FISH",
    "farm": "Pacific Ocean Fisheries",
    "stoke": "INSTOCK",
    "freshness": 5,
    "buyBy": ["Weight"],
    "deliveryDays": 3,
    "deliveryCoast": 0.7,
    "deliveryAria": "Nationwide",
    "maxKgs": 25,
    "description": "Fresh wild-caught salmon fillets, rich in Omega-3.",
    "detailDescription": "Our salmon is sustainably sourced and perfect for baking, grilling, or pan-searing.",
    "rate": 4.9,
    "tax": 7,
    "createdAt": "2025-01-06T10:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-07T15:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Frozen Tilapia Fillets",
    "image": [
      "https://i5.walmartimages.com/seo/Great-Value-Frozen-Tilapia-Skinless-Boneless-Fillets-2-lb-Bag_5414ca23-01a6-423e-9582-5714f29683bb.003faad4868b422fa265412e7e77c14c.jpeg",
      "https://chefsbox.net/cdn/shop/products/tilapiafilet_800x.jpg?v=1618586288",
      "https://chefsfreshfish.com/cdn/shop/products/DSC_0384.jpg?v=1588883838"
    ],
    "price": 5.99,
    "SKU": 10200456,
    "category": "MEATANDFISH",
    "subcategory": "FISH",
    "farm": "Blue Lake Fisheries",
    "stoke": "EXPECTEDSOON",
    "freshness": 30,
    "buyBy": ["Bag"],
    "deliveryDays": 4,
    "deliveryCoast": 0.12,
    "deliveryAria": "Nationwide",
    "maxKgs": 50,
    "description": "High-quality frozen tilapia fillets.",
    "detailDescription": "Convenient and versatile, our frozen tilapia is a great source of lean protein.",
    "rate": 4.6,
    "tax": 4,
    "createdAt": "2025-01-03T12:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-06T14:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Fresh Broccoli",
    "image": [
      "https://bragafresh.com/wp-content/uploads/2022/01/12oz-BF-Broccoli-Florets-Front-1242x1242-c-default.jpg",
      "https://www.allrecipes.com/thmb/01OsKBnYA8USlkV4Mqm6543C9fo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-691088799-2000-16d197c7cb4e4c48bb518e3931f52a98.jpg",
      "https://www.elizabethrider.com/wp-content/uploads/2020/11/How-to-Cook-Broccoli-Chart.jpg"
    ],
    "price": 2.99,
    "SKU": 10200567,
    "category": "FRUITANDVEGETABLES",
    "subcategory": "VEGETABLES",
    "farm": "Green Valley Farms",
    "stoke": "INSTOCK",
    "freshness": 7,
    "buyBy": ["Weight"],
    "deliveryDays": 2,
    "deliveryCoast": 0,
    "deliveryAria": "Local Only",
    "maxKgs": 20,
    "description": "Fresh, green broccoli rich in vitamins and minerals.",
    "detailDescription": "Sustainably grown, our broccoli is crisp and perfect for steaming or roasting.",
    "rate": 4.8,
    "tax": 2,
    "createdAt": "2025-01-02T09:00:00.000Z",
    "createdBy": "Admin2",
    "updatedAt": "2025-01-06T10:00:00.000Z",
    "updatedBy": "Admin2"
  },
  {
    "name": "Organic Carrots",
    "image": [
      "https://calorganicfarms.com/wp-content/uploads/2018/01/IMG_6239_rainbow_bunch.jpg",
      "https://calorganicfarms.com/wp-content/uploads/2017/10/Bunch-Carrots.jpg",
      "https://www.nutriharvest.com/cdn/shop/articles/carrots2_94041803-d158-41d7-8db2-57e6f2a1bb88.png?v=1712253710&width=1100"
    ],
    "price": 3.49,
    "SKU": 10200678,
    "category": "FRUITANDVEGETABLES",
    "subcategory": "VEGETABLES",
    "farm": "Fresh Earth Organics",
    "stoke": "INSTOCK",
    "freshness": 10,
    "buyBy": ["Bag"],
    "deliveryDays": 3,
    "deliveryCoast": 0.15,
    "deliveryAria": "Nationwide",
    "maxKgs": 15,
    "description": "Sweet and crunchy organic carrots.",
    "detailDescription": "Ideal for snacking or cooking, our organic carrots are naturally grown and pesticide-free.",
    "rate": 4.7,
    "tax": 3,
    "createdAt": "2025-01-04T10:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T11:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Baby Carrots",
    "image": [
      "https://cdn11.bigcommerce.com/s-rl94rv7pw2/images/stencil/1280x1280/products/792/819/thumbnail__48239.1736809262.png?c=1",
      "https://www.allrecipes.com/thmb/VVOYE0eLa_0kcZXbsDqT-wnFI1U=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/107344-sweet-baby-carrots-DDMFS-4x3-a436e66e64de4901a13b66bf6cfba119.jpg",
      "https://www.foodnetwork.com/content/dam/images/food/fullset/2003/9/22/0/tm1a28_baby_carrots.jpg"
    ],
    "price": 3.49,
    "SKU": 10200678,
    "category": "FRUITANDVEGETABLES",
    "subcategory": "VEGETABLES",
    "farm": "Fresh Earth Organics",
    "stoke": "INSTOCK",
    "freshness": 10,
    "buyBy": ["Bag"],
    "deliveryDays": 3,
    "deliveryCoast": 0.07,
    "deliveryAria": "Nationwide",
    "maxKgs": 15,
    "description": "Sweet and crunchy organic carrots.",
    "detailDescription": "Grown on organic farms, these baby carrots are naturally sweet and packed with vitamins, making them a healthy choice for any meal.",
    "rate": 4.7,
    "tax": 3,
    "createdAt": "2025-01-04T10:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T11:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Tropical Mangoes",
    "image": [
      "https://www.pittmandavis.com/images/xl/red-mangos-delivered-051923.webp?v=2",
      "https://www.pittmandavis.com/images/l/PD24-FloridaMangoes.jpg?v=1",
      "https://www.pittmandavis.com/images/xl/PD24-TropicalMangoes_02.webp?v=1"
    ],
    "price": 7.99,
    "SKU": 10200890,
    "category": "FRUITANDVEGETABLES",
    "subcategory": "FRUIT",
    "farm": "Sunshine Tropics",
    "stoke": "EXPECTEDSOON",
    "freshness": 6,
    "buyBy": ["Piece"],
    "deliveryDays": 3,
    "deliveryCoast": 1.5,
    "deliveryAria": "Nationwide",
    "maxKgs": 25,
    "description": "Ripe and juicy tropical mangoes.",
    "detailDescription": "Sourced from tropical farms, our mangoes are bursting with sweetness and flavor.",
    "rate": 4.8,
    "tax": 4,
    "createdAt": "2025-01-04T14:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T16:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Coconut Milk",
    "image": [
      "https://thevegangrocer.com.ph/cdn/shop/files/61516EF2-1D82-4967-98A2-DAC1BCE9A10A.png?v=1720106759",
      "https://vaya.in/recipes/wp-content/uploads/2019/01/Coconut-Milk.jpg",
      "https://elavegan.com/wp-content/uploads/2016/08/Homemade-coconut-milk-recipe-500x500.jpg"
    ],
    "price": 4.99,
    "SKU": 10300222,
    "category": "DRINKS",
    "subcategory": "DRINKS",
    "farm": "Nature's Best Dairy",
    "stoke": "INSTOCK",
    "freshness": 14,
    "buyBy": ["Bottle"],
    "deliveryDays": 2,
    "deliveryCoast": 1.5,
    "deliveryAria": "Nationwide",
    "maxKgs": 5,
    "description": "Rich and creamy organic coconut milk, perfect for cooking and beverages..",
    "detailDescription": "Made from freshly pressed organic coconuts, this coconut milk is a great dairy-free alternative, ideal for curries, soups, smoothies, and desserts.",
    "rate": 3.8,
    "tax": 3,
    "createdAt": "2025-01-05T12:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T13:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Gluten-Free Protein Bar - Aloha",
    "image": [
      "https://rembrandt.ownit.co/p0kZnQdMqPdrabSKi2q7m.png?width=750&format=jpeg&quality=70&bgcolor=white",
      "https://m.media-amazon.com/images/I/91-wdLUvmlL._AC_UF1000,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/81KPdYMgDOL.jpg"
    ],
    "price": 2.99,
    "SKU": 10300444,
    "category": "SPECIALNUTRITION",
    "subcategory": "SPECIALNUTRITION",
    "farm": "Healthy Bites",
    "stoke": "INSTOCK",
    "freshness": 60,
    "buyBy": ["Piece"],
    "deliveryDays": 3,
    "deliveryCoast": 1.0,
    "deliveryAria": "Nationwide",
    "maxKgs": 30,
    "description": "Delicious and nutritious gluten-free protein bar.",
    "detailDescription": "Packed with high-quality protein and fiber, perfect for a quick energy boost.",
    "rate": 2.5,
    "tax": 4,
    "createdAt": "2025-01-03T10:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-07T11:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Organic Turmeric Powder",
    "image": [
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/nav/nav02132/y/14.jpg",
      "https://domf5oio6qrcr.cloudfront.net/medialibrary/15065/conversions/fa246ce0-054b-4892-bf30-5eb43cd938aa-thumb.jpg",
      "https://5.imimg.com/data5/SELLER/Default/2021/6/LB/YH/DT/102620522/turmeric-500x500.jpg"
    ],
    "price": 5.99,
    "SKU": 10300666,
    "category": "SPECIALNUTRITION",
    "subcategory": "SPECIALNUTRITION",
    "farm": "Spice World",
    "stoke": "INSTOCK",
    "freshness": 365,
    "buyBy": ["Pack"],
    "deliveryDays": 3,
    "deliveryCoast": 1.5,
    "deliveryAria": "Nationwide",
    "maxKgs": 20,
    "description": "Premium organic turmeric powder with high curcumin content.",
    "detailDescription": "Sourced from certified organic farms, our turmeric powder adds flavor and health benefits to your meals.",
    "rate": 4,
    "tax": 3,
    "createdAt": "2025-01-08T10:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-09T12:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Pure Desi Ghee",
    "image": [
      "https://pureticks.com/wp-content/uploads/2024/10/Desi-Ghee-2-2048-x-2048-scaled.jpg",
      "https://vaya.in/news/wp-content/uploads/2019/03/ghee-2.jpg",
      "https://media.istockphoto.com/id/1314481702/photo/frying-pan-and-bowl-with-ghee-butter-on-dark-wooden-table-flat-lay.jpg?s=612x612&w=0&k=20&c=c_veW6cpaw92oAykaRqNcCgYDifvdQzQR2V0HDlvVPo="
    ],
    "price": 12.99,
    "SKU": 10300777,
    "category": "SPECIALNUTRITION",
    "subcategory": "SPECIALNUTRITION",
    "farm": "Heritage Dairy",
    "stoke": "EXPECTEDSOON",
    "freshness": 180,
    "buyBy": ["Jar"],
    "deliveryDays": 5,
    "deliveryCoast": 2.0,
    "deliveryAria": "Nationwide",
    "maxKgs": 15,
    "description": "Traditional pure desi ghee made from grass-fed cow's milk.",
    "detailDescription": "Slow-cooked and handcrafted, this ghee is rich in vitamins and ideal for cooking or Ayurvedic use.",
    "rate": 3.5,
    "tax": 5,
    "createdAt": "2025-01-08T11:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-09T13:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Premium Organic Granola with Dark Chocolate & Coconut Taste",
    "image": [
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/npa/npa77198/v/11.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/npa/npa77198/l/12.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/ugc/20250207/d372e0b5-47bf-414a-beed-fc0414e7cb7f/l.jpeg"
    ],
    "price": 8.99,
    "SKU": 10400555,
    "category": "SPECIALNUTRITION",
    "subcategory": "SPECIALNUTRITION",
    "farm": "Organic Bites",
    "stoke": "INSTOCK",
    "freshness": 365,
    "buyBy": ["Pack"],
    "deliveryDays": 3,
    "deliveryCoast": 2.0,
    "deliveryAria": "Nationwide",
    "maxKgs": 15,
    "description": "Indulgent organic granola with Fair Trade dark chocolate and coconut flakes.",
    "detailDescription": "Crafted with whole grain oats, Fair Trade dark chocolate chunks, and creamy shredded coconut, this premium granola is a perfect blend of crunch and flavor. USDA Organic, Non-GMO, and Fair Trade Certified, it's a guilt-free indulgence that supports sustainable farming and responsible sourcing. Enjoy it as a snack, with yogurt, or as a topping for smoothie bowls.",
    "rate": 4.9,
    "tax": 3,
    "createdAt": "2025-01-15T09:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-16T11:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "California Gold Nutrition, Superfoods, Organic Chia Seeds",
    "image": [
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01217/v/26.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01217/l/27.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/cgn/cgn01217/l/23.jpg"
    ],
    "price": 6.99,
    "SKU": 10500234,
    "category": "SPECIALNUTRITION",
    "subcategory": "SPECIALNUTRITION",
    "farm": "California Gold Nutrition",
    "stoke": "INSTOCK",
    "freshness": 180,
    "buyBy": ["Pack"],
    "deliveryDays": 3,
    "deliveryCoast": 1.5,
    "deliveryAria": "Nationwide",
    "maxKgs": 20,
    "description": "Nutrient-rich organic chia seeds, perfect for smoothies, baking, and more.",
    "detailDescription": "Packed with omega-3 fatty acids, fiber, and protein, these organic chia seeds are a superfood staple. They can be blended into shakes, sprinkled over yogurt or oatmeal, or used in baking for a healthy boost. USDA Organic and Non-GMO, they offer clean nutrition for your daily wellness. Store in a cool, dry place and use within 6 months after opening.",
    "rate": 4.8,
    "tax": 3,
    "createdAt": "2025-01-18T08:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-19T10:00:00.000Z",
    "updatedBy": "Admin"
  },
  {
    "name": "Gerber, Cereal for Baby, Grain & Grow, 8+ Months, Oatmeal Banana Strawberry",
    "image": [
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/gbr/gbr07031/v/28.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/gbr/gbr07031/l/26.jpg",
      "https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/gbr/gbr07031/l/23.jpg"
    ],
    "price": 5.49,
    "SKU": 10600321,
    "category": "BABY",
    "subcategory": "BABY",
    "farm": "Gerber",
    "stoke": "INSTOCK",
    "freshness": 30,
    "buyBy": ["Pack"],
    "deliveryDays": 2,
    "deliveryCoast": 1.0,
    "deliveryAria": "Nationwide",
    "maxKgs": 10,
    "description": "Nutritious oatmeal cereal with banana and strawberry for babies 8+ months.",
    "detailDescription": "Gerber's Grain & Grow oatmeal cereal is made with whole grains and enriched with iron to support brain development. Featuring real banana flakes and strawberry bits, this cereal introduces new tastes and textures for growing babies. Non-GMO, kosher, and easy to prepare—just add liquid and serve. Store in a cool, dry place and use within 30 days after opening.",
    "rate": 4.7,
    "tax": 2,
    "createdAt": "2025-01-20T09:00:00.000Z",
    "createdBy": "Admin",
    "updatedAt": "2025-01-21T11:00:00.000Z",
    "updatedBy": "Admin"
  }
];

db.products.insertMany(products);

print("Products inserted successfully!");

// const bcryptjs = require('bcryptjs');
//
// const db = db.getSiblingDB("foodmarketbd");

// const hashedPassword = async (password) => {
//   const salt = await bcryptjs.genSalt(10);
//   return await bcryptjs.hash(password, salt);
// }

// print("Initial data inserting...");

// Дані для ініціалізації
// const users = [
//   {
//     firstName: "Admin",
//     lastName: "First",
//     username: "admin",
//     email: "admin@gmail.com",
//     phoneNumber: "1234567891234",
//     password: "K(75ie%Y",
//     role: "admin",
//     newsletterConsent: false,
//   },
//   {
//     firstName: "Admin",
//     lastName: "Second",
//     username: "admin2",
//     email: "admin2@gmail.com",
//     phoneNumber: "1234567891234",
//     password: "K(75ie%Y",
//     role: "admin",
//     newsletterConsent: false,
//   },
// ];

// db.products.insertMany(products);


// (async () => {
//   try {
//     const db = db.getSiblingDB("foodmarketdb"); // Задайте ім'я бази даних
//
//     const hashedUsers = await Promise.all(
//       users.map(async (user) => ({
//         ...user,
//         password: await hashedPassword(user.password),
//         createdAt: new Date(),
//         updatedAt: new Date(),
//       }))
//     );
//
//     // Додаємо користувачів до колекції
//     db.users.insertMany(hashedUsers);
//
//     console.log("Users added successfully with hashed passwords!");
//   } catch (error) {
//     console.log("Error during initialization:", error);
//   }
// })();

print("Initial data inserted successfully!");
